spring:
  
  profiles: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location : /home/optimus/uploadedfile/
         
server:
  port: 8080
  tomcat: 
     max-threads: 100
  