spring:
  
  profiles: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location : /home/optimus/uploadedfile/

eureka:
  client:
    enabled: false
    serviceUrl:
       defaultZone: http://localhost:8761/eureka
  instance: 
     instance-id:  ${spring.application.name}:${spring.application.instance_id:${random.value}}
         
server:
  port: 8080
  tomcat: 
     max-threads: 400
     
